language: go

go:
  - 1.2.x
  - 1.6.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.14.x
  - tip

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

dist: bionic

env:
  jobs:
    - GOARCH=386
    - GOARCH=amd64

script:
  - go test -v -cover ./... || go test -v ./...
